server:
  port: 8802

spring:
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kaseradb
    username: sauravS
    password: saurav@simmi

  jpa:
    hibernate:
      ddl-auto: update
    database: MYSQL

  mail:
    host: smtp.gmail.com
    port: 587
    username: saurav24021998@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true